apiVersion: v1
kind: Service
metadata:
  name: pong-front-svc
  namespace: random-pong
spec:
  type: NodePort
  selector:
    app: pong-front
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 3000