apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-back
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-back
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-back
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: todopw
        - configMapRef:
            name: postgres-db-config
        image: PROJECT/IMAGE
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3002
          initialDelaySeconds: 20
          periodSeconds: 5
        name: todo
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 150m
            memory: 100Mi
