apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: randomstring-app
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: randomstring-svc
          servicePort: 2345
      - path: /random
        backend:
          serviceName: randomstring-svc
          servicePort: 2345