apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pixabay-apikey
  namespace: default
spec:
  encryptedData:
    API_KEY: AgBRm1Y+9K2yo6DpGUJ0SYQWROmIwREmAALZlOb4FDSfDmbp1tpAZiAbt7OQQrOJSrigT+8yJHpPPakQPz+CILm145BDErnF/rj4TjFLAnWSuL5+gqBiZMe2FYR1VnVyjRuF09AZKmhc18VsHSgRDtMosTvlSZ6lUibE3tcQmN95tB+DO1pfYIXTBE9PXTeTOV+5WIlUiTqWAopSlJtyJmrWF8Xjf31HI0La/GhiaGZb1HYD0YK4oIy8cuFRU/iNAfUVV/bv6ulJaTuWiD4sCEETX2BrG0/Hu4WHUaMDWrhBfg9pDoESKiLf40oPyYPgnoT7Nbi5QvBpeMXpk2l+FtrgVtiatruRvv+RFOh7Ofvd6fx8nG0087ybHZH57OJni3iLDo4i12nJvFWKsHQpTPtC4tZKoBsLkIsk9IKKNDjpxye5G3AstNR7zqsjIRLROzpFTs6u+brhOylfhPs0p8l01jm+1WXXS4OtTnFc9HkQrTZuOhPFt3PTpa+w0lPrhfHqmhyktmv3kb2NQdpQRsjBmAlupsE5CkkLXpzFT2YQL5tOrGttfKtaOGLMME26J4sMfiv65eRPPgNeH/nocIyH7knl0LC1HxDhDHkFxcOeLNH0WQRhdMDy8qluaDFkY5qNUvOX56sxlPs746kgdQgZp2MedfVticOn3x2ErfTn0BEAzAIvMkXXERmIxTw4e8ptayKMhHTDKhBTQ1DriafdjPTNbDijcFLIFZuY/cRzKJVRIjdrAcCdXIY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pixabay-apikey
      namespace: default

