apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/cronjob.yaml
- manifests/horizontalpodautoscaler.yaml
images:
  - name: PROJECT/IMAGE
    newName: epylkkan/training_kubernetes_devops:402wiki
    #newName: epylkkan/training_kubernetes_devops:209wiki

    
