apiVersion: apps/v1
kind: Deployment
metadata:
  name: random
  namespace: random-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random
  template:
    metadata:
      labels:
        app: random
    spec:
      containers:
        - name: random-reader
          image: epylkkan/training_kubernetes_devops:309reader
          volumeMounts: 
          - name: node-env-file
            mountPath: "/usr/src/app"
            readOnly: false
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
      volumes:
        - name: node-env-file
          configMap:
            name: node-configmap

          

