apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-back
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-back
  template:
    metadata:
      labels:
        app: todo-back
    spec:
      containers:
        - name: todo
          image: epylkkan/training_kubernetes_devops:210backend
          volumeMounts: # Mount volume
          - name: todopw
            mountPath: "/usr/src/app/todopw"
            readOnly: false
          envFrom:
            - secretRef:
                name: todopw
            - configMapRef:
                name: postgres-db-config
      volumes:
        - name: todopw
          secret: 
            # name: todopw
