apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pong-svc
  namespace: random-pong
spec:
  template:
    metadata:
      # annotations:
      #   autoscaling.knative.dev/minScale: "1"
      name: pong-svc-v1
    spec:
      containers:
        - image: epylkkan/training_kubernetes_devops:505pingpong-front
  traffic: # traffic enables us to split traffic between multiple revisions!
  - revisionName: pong-svc-v1
    percent: 100
    