apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pong-front-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pong-front
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50