apiVersion: v1
kind: Service
metadata:
  name: random-np-svc
  namespace: random-pong
spec:
  type: NodePort
  selector:
    app: random
  ports:
    - port: 2345
      name: random
      protocol: TCP
      targetPort: 3003