apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/broadcaster.yaml
- manifests/telegram.yaml
images:
  - name: PROJECT/IMAGE
    newName: epylkkan/training_kubernetes_devops:406-71broadcaster
