apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: random-pong
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - port: 2345
      name: pong
      protocol: TCP
      targetPort: 3000
