apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: controller-account
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: controller
          image: epylkkan/training_kubernetes_devops:501controller
          volumeMounts:
            - name: shared-data
              mountPath: /usr/src/app/data
          resources:
            limits:
              memory: "128Mi"
              cpu: "125m"
        - name: server
          image: halverneus/static-file-server:latest          
          volumeMounts:
            - name: shared-data
              mountPath: /web
          resources:
            limits:
              memory: "128Mi"
              cpu: "125m"      