apiVersion: v1
kind: Service
metadata:
  name: random-svc
  namespace: random-pong
spec:
  type: ClusterIP
  selector:
    app: random
  ports:
    - port: 2347
      name: random
      protocol: TCP
      targetPort: 3003

