apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-front
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-front
  template:
    metadata:
      labels:
        app: todo-front
    spec:
      containers:
        - name: todo-front
          image: epylkkan/training_kubernetes_devops:202frontend
