apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-back
  namespace: random-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-back
  template:
    metadata:
      labels:
        app: pong-back
    spec:
      containers:
        - name: pong-back
          image: epylkkan/training_kubernetes_devops:401-12pingpongbackend
          readinessProbe:
           periodSeconds: 5
           initialDelaySeconds: 20
           timeoutSeconds: 3
           successThreshold: 1
           httpGet:
             path: /healthz
             port: 3002
          envFrom:
            - secretRef:
                name: dbpw
            - configMapRef:
                name: postgres-db-config
