apiVersion: v1
kind: Service
metadata:
  name: pong-back-svc
  namespace: random-pong
spec:
  type: ClusterIP
  selector:
    app: pong-back
  ports:
    - port: 2346
      name: pong-back
      protocol: TCP
      targetPort: 3002
