apiVersion: v1
kind: Service
metadata:
  name: todo-app-with-frontend-and-backend
  namespace: todo
spec:
  type: LoadBalancer
  selector:
    app: todo-front
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000