apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu
  namespace: todo
spec:
  metrics:
  - name: cpu
    initialDelay: 10m
    successCondition: result < 0.5
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1629-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(sum(sum by (pod) (rate(container_cpu_usage_seconds_total{namespace="todo"}[1m]))))