apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-back
  namespace: random-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-back
  template:
    metadata:
      labels:
        app: pong-back
    spec:
      containers:
        - name: pong-back
          image: epylkkan/training_kubernetes_devops:207backend
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
          volumeMounts: # Mount volume
          - name: dbpw
            mountPath: "/usr/src/app/dbpw"
            readOnly: false
          envFrom:
            - secretRef:
                name: dbpw
            - configMapRef:
                name: postgres-db-config      
      volumes:
        - name: dbpw