apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pong-back-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pong-back
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50