# PostgreSQL StatefulSet ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
  namespace: random-pong
  labels:
    app: postgresql-db
data:
  POSTGRES_DB: pongdb
  POSTGRES_USER: pong
  POSTGRES_PASSWORD: pong
  PGDATA: /data/pgdata