apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-front
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-front
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-front
    spec:
      containers:
      - image: PROJECT/IMAGE
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
        name: todo-front
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 150m
            memory: 100Mi
---
