apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-front
  namespace: random-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-front
  template:
    metadata:
      labels:
        app: pong-front
    spec:
      containers:
        - name: pong-front
          image: epylkkan/training_kubernetes_devops:302-1frontend