apiVersion: v1
kind: Service
metadata:
  name: pingpong-np-svc
  namespace: random-pong
spec:
  type: NodePort
  selector:
    app: pong-front
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
