name: Delete from GKE

on:
  workflow_dispatch:
    
env:
  GKE_CLUSTER: dwk-kube    # TODO: update to cluster name
  GKE_ZONE: europe-north1-b   # TODO: update to cluster zone
  DEPLOYMENT_NAME: todo-delete # TODO: update to deployment name

jobs:
  delete-from-GKE:
    name: delete from GKE
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: epylkkan/devops-with-kubernetes_hy2021
        path: master

    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true
    
    - run: gcloud --quiet auth configure-docker

    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "${{ secrets.GKE_PROJECT }}"
        
    - name: Delete
      run: |-
        kubectl delete namespace ${GITHUB_REF#refs/heads/} || true        