name: Delete from GKE

on:
  workflow_dispatch:
    
env:
  GKE_CLUSTER: dwk-kube    # TODO: update to cluster name
  GKE_ZONE: europe-north1-c   # TODO: update to cluster zone
  DEPLOYMENT_NAME: todo-delete # TODO: update to deployment name
  #IMAGE: todo-front

jobs:
  delete-from-GKE:
    name: delete from GKE
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: epylkkan/devops-with-kubernetes_hy2021
        path: master

    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true
    
    - run: gcloud --quiet auth configure-docker

    #- name: Create image names
    #  run: |-
    #    echo "IMAGE_WITH_TAG=gcr.io/${{ secrets.GKE_PROJECT }}/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" >> $GITHUB_ENV

    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "${{ secrets.GKE_PROJECT }}"
    
    #- name: Set up Kustomize
    #  run: |-
    #    cd ./master/part3/3.04/frontend
    #    curl -sfLo kustomize.tgz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv3.7.0/kustomize_v3.7.0_linux_amd64.tar.gz
    #    tar xf kustomize.tgz
    #    chmod u+x ./kustomize
        
    - name: Delete
      run: |-
        kubectl delete namespace ${GITHUB_REF#refs/heads/} || true
#        cd ./master/part3/3.04/frontend
#        kubectl config set-context --current --namespace=${GITHUB_REF#refs/heads/}
#        ./kustomize edit set namespace ${GITHUB_REF#refs/heads/}        
#        ./kustomize edit set image PROJECT/IMAGE=$IMAGE_WITH_TAG
#        kubectl delete -k .
        